package sbnz.integracija;
import dtos.CreateOrderDto;
import dtos.OrderItemDto;
import demo.facts.BookCategory;

rule "10-percent-discount"
    agenda-group "orderDiscount"
    lock-on-active true
    when
        $o : CreateOrderDto(orderItems.size() >= 3)
    then
        insert (new Double($o.getTotalPrice() * 0.9));

end

rule "15-percent-discount"
    agenda-group "orderDiscount"
    lock-on-active true
    when
        $o : CreateOrderDto(orderItems.size >= 5)
    then
        insert (new Double($o.getTotalPrice() * 0.85));

end

rule "Apply-max-order-discount"
    agenda-group "orderDiscount"
    when
        $minPrice : Double() from accumulate( $d : Double(), min( $d ) )
        $o : CreateOrderDto( orderItems.size >= 3 )
    then
        $o.setTotalPrice( $minPrice );
end

rule "Quantity-discount"
    agenda-group "itemDiscount"
    lock-on-active true
    when
        $oi : OrderItemDto( quantity >= 2)
    then
        insert (new Double($oi.getPrice() * 0.9));
end

rule "Large-order-discount"
    agenda-group "itemDiscount"
    lock-on-active true
    when
        $oi : OrderItemDto(price > 3000 )
    then
        insert (new Double($oi.getPrice() * 0.95));
end

rule "Educative-book"
    agenda-group "itemDiscount"
    lock-on-active true
    when
        $oi : OrderItemDto(price > 2000, genre.name == "Education" )
    then
        insert (new Double($oi.getPrice() * 0.93));
end

rule "Apply-max-item-discount"
    agenda-group "itemDiscount"
    when
        $minPrice : Double() from accumulate( $d : Double(), min( $d ) )
        $oi : OrderItemDto( )
    then
        $oi.setPrice( $minPrice );
end



